### ISSUE TITLE
Error while trying to download my addon from the workshop.

### ISSUE THREAD

**Issue by dvdvideo1234** [magnusjjj/gmadget#3] opened 2017-04-24 10:50 UTC
Hello, 

I am executing the following
```
gmadget --singleids 287012681
```
And it crashes like shown below. I am expecting it to download my addon.
In fact even with the example shown in the readme it crashes also.
[![error_crash.jpg](https://s14.postimg.org/oudxqzgc1/error_crash.jpg)](https://postimg.org/image/csijwu73h/)

**Comment by magnusjjj** [comment] 2017-04-24 16:30
Hi!

Always happy to help, though this one looks odd. Do you have any other means of contacting you? :)
Do you have any other version of python installed already?

That crash means that python failed. Like, the interpreter, not my code. Which is really wierd, not seen that before at all, so will have to see if we can find a way to reproduce this :).

**Comment by magnusjjj** [comment] 2017-04-24 16:34
Yeah, for me it works just fine. I downloaded and reinstalled it from scratch, and it works fine. There is a couple of things we could try, like updating the bundled python version, but for that, I would need your direct help :)

**Comment by Xeddius** [comment] 2021-04-12 09:28
Fails to download with error below:

```
Active code page: 65001
Getting a list of the mods inside collection id 2172150790
Traceback (most recent call last):
  File "gmaddown_console.py", line 75, in <module>
    json_demystified = json_demystified["response"]["collectiondetails"][0]["children"];
KeyError: 'children'
```

**Comment by magnusjjj** [comment] 2021-04-12 12:38
Xeddius, for some reason your collection returns, with the steam workshop api, that there is no such collection.
Yet, if I go to that collection in steam's browser, it's there.

I have no real clue what is going on with that.

Can you check if there is something wonky going on with, oh, uh, permissions on the workshop collections, things of that nature?

**Comment by magnusjjj** [comment] 2021-04-12 12:43
Oh, your steam workshop collection is set to unlisted. Might that be it? :)

**Comment by magnusjjj** [comment] 2022-06-17 18:54
Closing this because no answer was given, and need to work on further things :)

**Closed as completed** 2022-06-17 18:54 UTC
